New filter to customize retrieved event list
eventespresso/ee4-events-calendar pull request #10
Opened 2020-10-13 20:39 UTC by davefx

New filter to customize the retrieved event list, allowing full customization of the list obtained from the database, allowing the dynamic generation of events, or the removal of specific events.

Also, allowing the cancellation of the insertion of a event into the JSON if the already existing filter FHEE__EE_Calendar__get_calendar_events__calendar_datetime returns false.

## Problem this Pull Request solves

We need to create events dynamically. Also, we need to filter out some of the retrieved events on conditions that must be evaluated in PHP (cannot be determined by a simple SQL query).

Also, we need to allow discarding some events depending on their calculated text just before inserting them into the returned JSON.

## How has this been tested

The change introduces a new filter to allow further customization of the retrieved JSON event list. Unless this filter is used, no extra changes will happen.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [] My code has proper inline documentation.

2020-12-21 04:07 UTC, davefx commented
@eeteamcodebase @manzoorwanijk Hi! Would you consider merging this PR?

2020-12-22 18:01 UTC, tn3rb requested changes
Hi David, 

thanks for another great contribution 👍🏻 

have one minor suggestion for improvement

2020-12-22 18:01 UTC, tn3rb commented on EED_Espresso_Calendar.module.php
> +                if ( $calendar_datetime ) {
great addition 💯 

should never trust results from a filter.

that said, an instanceof check is better because it proves the existence of the exact object we want

```suggestion
                if ($calendar_datetime instanceof EE_Datetime_In_Calendar) { 
```

2020-12-23 12:20 UTC, manzoorwanijk reviewed
@davefx can you please fix the lints as shown in PR checks?

2020-12-23 13:07 UTC, manzoorwanijk approved these changes
Thank you for the lint fix.

2020-12-23 13:08 UTC, merged